# Generated by Django 5.2 on 2025-07-03 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_add_stagiaire_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('base_path', models.CharField(help_text='Base directory for calculation files', max_length=500)),
                ('projects_file', models.CharField(blank=True, help_text='Path to projects parquet file', max_length=500)),
                ('employees_file', models.CharField(blank=True, help_text='Path to employees parquet file', max_length=500)),
                ('summary_stats', models.JSONField(blank=True, default=dict, help_text='Cached calculation summary statistics')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='IP address of user who initiated calculation', null=True)),
                ('user_identifier', models.CharField(blank=True, help_text='Optional user identifier', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='billing_cal_status_8d1014_idx'), models.Index(fields=['user_ip', '-created_at'], name='billing_cal_user_ip_48d9ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCalculationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(db_index=True)),
                ('user_identifier', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.calculationrun')),
            ],
            options={
                'unique_together': {('user_ip', 'user_identifier')},
            },
        ),
    ]
