# Generated by Django 5.2.3 on 2025-08-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_calculationrun_usercalculationpreference'),
    ]

    operations = [
    ]
