# Generated by Django 5.0.2 on 2025-08-07 17:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20250805_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=100)),
                ('preferred_dashboard', models.CharField(default='dashboard1', max_length=50)),
                ('show_archived', models.BooleanField(default=False)),
                ('default_chart_type', models.CharField(default='bar', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usercalculationpreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercalculationpreference',
            name='preferred_run',
        ),
        migrations.RemoveIndex(
            model_name='calculationrun',
            name='billing_cal_status_8d1014_idx',
        ),
        migrations.RemoveIndex(
            model_name='calculationrun',
            name='billing_cal_user_ip_48d9ca_idx',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='base_path',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='employees_file',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='projects_file',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='summary_stats',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='user_identifier',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='user_ip',
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='data_directory',
            field=models.CharField(default='default_directory/', max_length=500),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='heures_filename',
            field=models.CharField(default='default_heures.txt', max_length=255),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='mafe_filename',
            field=models.CharField(default='default_mafe.txt', max_length=255),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='period_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='period_string',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='period_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='total_adjusted_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='total_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='total_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='total_variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calculationrun',
            name='run_id',
            field=models.CharField(db_index=True, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='calculationrun',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('updated', 'Updated with Adjustments')], default='processing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='calculationrun',
            index=models.Index(fields=['created_at'], name='billing_cal_created_0a8540_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationrun',
            index=models.Index(fields=['status'], name='billing_cal_status_6f4ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationrun',
            index=models.Index(fields=['period_year', 'period_month'], name='billing_cal_period__399af0_idx'),
        ),
        migrations.AddField(
            model_name='userdashboardpreference',
            name='preferred_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.calculationrun'),
        ),
        migrations.DeleteModel(
            name='UserCalculationPreference',
        ),
        migrations.AlterUniqueTogether(
            name='userdashboardpreference',
            unique_together={('user_identifier',)},
        ),
    ]
